// LOOP SLEEP IN MS
#define LOOPSLEEP 50 // Always less than 1000

const int TICKSSECOND = 1000/LOOPSLEEP;

// Scheduler frequencies
const int EVERY_20_SECONDS = TICKSSECOND*20;
const int EVERY_10_SECONDS = TICKSSECOND*10;
const int EVERY_6_SECONDS  = TICKSSECOND*6;
const int EVERY_4_SECONDS  = TICKSSECOND*4;
const int EVERY_2_SECOND   = TICKSSECOND*2;
const int EVERY_SECOND     = TICKSSECOND*1;
const int EVERY_500MS      = TICKSSECOND*0.5;
const int EVERY_1_HOUR     = TICKSSECOND*60*60;
